[package]
name = "project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
restaurant = {path = "../restaurant"}

#lib 어플리케이션 경로를 무조건 알려주어야 한다.